### ISSUE TITLE
fortran idba_scopa does not reset the dba format (v6 to v7)

### ISSUE THREAD

**Issue by cmarsigli** [ARPA-SIMC/dballe#108]
ier=idba_presentati(idbhandle,database)
    ier=idba_preparati(idbhandle,handle, &
    "write","write","write")
    ier=idba_scopa(handle,"repinfo.csv")
    ier=idba_fatto(handle)
    ier=idba_arrivederci(idbhandle)

starting from a db with v6 format, the db does not become the default v7 format by executing these lines

**Comment by pat1** [comment]
linked to #97

**Comment by spanezz** [comment]
Automatically converting the database at `idba_scopa` time is quite difficult at the moment, because when `idba_presentati` is run, it connects to the database, detects its format and selects the driver to use for all other operations on the handle.

This means that if `idba_presentati` is run on a V6 database, it selects the V6 driver, and then it's the V6 driver that handles the `idba_scopa`.

Changing driver in the middle of a session is currently not supported.

Wiping a database changing its format can currently be done on the commandline with dbadb like this:
```
dbadb wipe --disappear --url=…
dbadb wipe --url=…
```

Let me know if being able to do it on the command line is sufficient for what you need.

**Comment by pat1** [comment]
ok, to be closed for me
