### ISSUE TITLE
Transactions and idba_scopa

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/dballe#110]
Hello,

since `idba_scopa` is removing all database tables and recreating them, it cannot work inside a transaction. dballe currently rolls back the transaction before `idba_scopa`, and restarts a new one afterwards.

I would like to turn `idba_scopa` into an alias for `remove_all`, and to have a way for doing database setup at `idba_presentati`. This will also allow to have conversions from V6 to V7 as requested in #108. This will allow `idba_presentati` to optionally gain the ability of doing something like `dbadb --wipe-first`.

Currently `idba_presentati` has two unused parameters: one of them could become a flag to activate features like this. Something like:
```
idba_presentati(dbhandle, "dbtype://info", "wipe", DBA_MVC)
```

For existing application, `idba_scopa` will become the same as `idba_remove_all`. An existing application that needs to create/recreate the database at startup, will need to be recompile to add `"wipe"` to `idba_presentati`.

This is my proposal. Would it work for you?

**Comment by dcesari** [comment]
If I understand correctly it is an enhancement, since it adds possibility without removing anything.
I see however the drawback that, with a plain implementation, all the fortran programs  will have to be rewritten to support the 3rd argument, even when it is not needed (we use a fortran `MODULE` which imposes a strict API). An alternative would be to turn `FUNCTION idba_presentati` in `dballef.f90` into a generic interface to the two possible idba_presentati with 2 and 3 arguments or consider the third argument optional (I can contribute this piece of code), so that the transition will be smoother and we do not need a strong mutual version dependency between packages, although a fortran recompilation will be probably needed in any case.
So, the conclusion is: I agree if we allow the double Fortran interface with 2/3 arguments to `idba_presentati`.

**Comment by spanezz** [comment]
Oh, good point, I had overlooked that we did change `idba_presentati` to only take url also at the ABI level. `doc/fapi_connect.md` still lists the old form with two `DBA_MVC` arguments and I referred to that. I have now fixed it in the `issue67` branch.

Another option, to avoid changing the API or needing to recompile, is to implement this feature at the DB URL level. For example, adding `&dballe=wipe` to the URL to turn on the `--wipe-first` equivalent.

**Comment by spanezz** [comment]
The only behavioural change, besides the enhancement, that I see in this proposal is that a fortran program which started with `idba_scopa` as the first thing, since it does recreate the database structure, it is currently able to work on a database with no dballe tables. After the change it will get an error because the database has not been initialised with dballe tables, and either it uses the new wipe feature in `presentati`, or it needs `dbadb wipe` to be invoked before it starts.

**Comment by dcesari** [comment]
It would be great to have it in the url, then we could control the wipe in the libsim tools through command line arguments. I cannot really judge on the other point about the behavioural change, but in worst case we can do a `dbadb wipe` externally if it's a problem to modify fortran code or recompile.

**Comment by spanezz** [comment]
Sounds like a plan

**Comment by spanezz** [comment]
Done in 417b472996896a391d969e456e03862b39f56e08

**Comment by dcesari** [comment]
Is this new behavior documented anywhere? By looking at the commit we guessed that the correct query string is `?wipe=true` raher than `?dballe=wipe`. @edigiacomo @brancomat it is worth checking that applications using libsim v7d_transform/vg6d_getpoint e.g. with output to a non existing sqlite DB file, continue working as expected.
N.B. this is related to https://github.com/ARPA-SIMC/libsim/issues/55

**Comment by spanezz** [comment]
I documented this in [`doc/fapi_connect.md`](https://github.com/ARPA-SIMC/dballe/blob/master/doc/fapi_connect.md#url-actions), it looks like I forgot to close the ticket afterwards.
