### ISSUE TITLE
copy record in python api

### ISSUE THREAD

**Issue by lidiabressan** [ARPA-SIMC/dballe#113]
reading and writing from one db to another:
```
 for row in db1.query_data(dballe.Record(lon=lon_staz, lat=lat_staz, var=var)):
    db2.insert_data(row, can_replace=True, can_add_stations=True)  
 Traceback (most recent call last):
  File "prepara_db_per_verifica.py", line 163, in <module>
    db2.insert_data(rec, can_replace=True, can_add_stations=True)  
 OSError: cannot execute the query:FOREIGN KEY constraint failed
```
my solution:
```
 for row in db1.query_data(dballe.Record(lon=lon_staz, lat=lat_staz, var=var)):
    del row['ana_id']
    del row['context_id']
    db2.insert_data(row, can_replace=True, can_add_stations=True)  
```
ana_id and context_id should not be used by the user. Wouldn't it be better to remove them from dballe.Record?

thanks

**Comment by spanezz** [comment]
Your solution is correct. I would like to get rid of them in `dballe.Record`, but as far as I know there is code that uses `DB-All.e` that stores `ana_id` instead of the rest of the station information, in order to reduce memory usage and make updating data later a bit faster.
This *does* break things when dealing with multiple databases, and it should at least be documented. Since you experienced this issue, would you be able to identify a place in the documentation where you would have been likely to find information about this, and it would have helped you?

Alternatively, I could try and special case `ana_id` and `context_id` so that they are stored outside the record, and only accessed when one queries them, or only fill them if the user request it somehow. This would go quite well with the ideas being discussed in #114

**Comment by lidiabressan** [comment]
Documentation? Where?

**Comment by spanezz** [comment]
Good point. There is documentation mostly for Fortran API at https://github.com/ARPA-SIMC/dballe/blob/master/doc/fapi.md
For python, there is some documentation that is built when the package is compiled, but is not available on github. It should be locally available in `/usr/share/doc/*dballe*/`
I think you answered my question, though: your experience cannot suggest a particularly good place, because you had to learn to use `DB-All.e` without documentation.
It's a good opportunity to improve on the documentation situation.

**Comment by edigiacomo** [comment]
```
import dballe

db1 = dballe.DB.connect_from_url("sqlite://:memory:")
db2 = dballe.DB.connect_from_url("sqlite://:memory:")
db1.reset()
db2.reset()

with open("rmap_claster_20181214133033588476209.bufr") as fp:
    db1.load(fp)

for data in db1.query_data({}):
    db2.insert_data(data, can_replace=True, can_add_stations=True)
```
Raises
```
    db2.insert_data(data, can_replace=True, can_add_stations=True)
TypeError: Expected dict or None
```

And `data.query` is not a proper object to insert (e.g. data.query[`var`] is a `str`, not a `var`).

**Comment by spanezz** [comment]
Good catch. I can implement `Cursor.data` similar to `Cursor.query`, and possibly implement reading the Cursor directly from `insert_station_data` and `insert_data`, if one doesn't need to store the intermediate result but is just copying data.

**Comment by edigiacomo** [comment]
Nice!
