### ISSUE TITLE
No attributes found in python 3.3.2 module

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/dballe#14]
```
$ python3 --version
Python 3.3.2
$ python3 -c "import dballe; print(dir(dballe))"
['__doc__', '__initializing__', '__loader__', '__name__', '__package__', '__path__']
```

```
$ python3 --version
Python 3.4.3+
$ python3 -c "import dballe; print(dir(dballe))"
['Cursor', 'DB', 'Record', 'Var', 'Varinfo', 'Vartable', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_dballe', 'absolute_import', 'describe_level', 'describe_trange', 'var', 'varinfo', 'wreport']
```

**Comment by spanezz** [comment]
I do not have a python 3.3.2 to try. What platforms are actually requiring it?

**Comment by edigiacomo** [comment]
Fedora 20

**Comment by spanezz** [comment]
Ok, what happens is that there is a dballe directory in one of sys.path which isn't the dballe python module, and the dballe python module is not in sys.path.

This happens, for example, if you run python3 inside the dballe sources directory without setting PYTHONPATH to $top_srcdir/python.

Python 3.3 changed import logic to allow loading modules from directories that do not have a __init__.py file inside them, but if somewhere in sys.path there is a directory that HAS the __init__.py file inside, only that one will be used.

I suspect that in your case python is using the dballe/ directory with the library sources as a module, which then contains nothing because there are no python files in there. Once the actual python module is present in sys.path, this does not happen anymore because it does contain __init__.py. In python2 you would have had an ImportError error; in python 3.3+ it seems to be ok importing something entirely unrelated :/

I found some more details about the situation here:
http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html
