### ISSUE TITLE
"Transaction within transaction" error with sequential queries

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/dballe#145]
```
import dballe


db = dballe.DB.connect_from_file("db.sqlite3")

for rec in db.query_data({}):
    pass

for rec in db.query_data({}):
    pass
```

Raises an exception:

```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    for rec in db.query_data({}):
OSError: executing BEGIN:cannot start a transaction within a transaction
```

**Comment by spanezz** [comment]
Change it with:
```
with db.query_data() as cursor:
    for row in cursor:
       ...
```
or with:
```
with db.transaction() as tr:
    for rec in tr.query_data({}):
        pass
    for rec in tr.query_data({}):
        pass
```
A Cursor maintains a pointer to the transaction, and 'rec' is still existing outside of the for loop, which means that the transaction is never really ended, and you're indeed, at the second `query_data`, opening a transaction inside a transaction.

I'm not sure how to do this right at the binding level, besides promoting scoping of cursors with `with`, or explicit use of transactions, rather than doing operations via the DB object.

**Comment by edigiacomo** [comment]
Ok, now I understand, thank you!
