### ISSUE TITLE
use of explorer in a big DB with mobile stations

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#147]
The use of Explorer in a big DB with mobile stations shoud going to stall due to very big number of stations.
We have to think to a solution similar to arkimet implementation.

**Comment by edigiacomo** [comment]
If I'm not missing something, the db::Summary of a DB with mobile stations is big as the DB itself.

Related issue #122.

**Comment by spanezz** [comment]
I propose that, when iterating results of a query_summary:
* a *fixed* station has `ident` unset. A *mobile* station has `ident` set. This is the only distinction between a fixed and a mobile station, as has always been at the core of the DB-All.e APIs.
* *mobile* stations are grouped by ident, and their coordinates are summarised into a bounding box
* you get all the *fixed* stations first, then all the *mobile* stations
* for a *fixed* station, `mobile` is set to 0, and `lat` and `lon` have values
* for a *mobile* station, `mobile` is set to 1, and `latmin`, `latmax`, `lonmin`, `lonmax` have values (`lat` and `lon` are either not set, or give an error if queried)
* *mobile* stations have no `and_id` set
* when connecting to a database, it is possible to specify a "force fixed stations" option (possible via a `?stations=fixed` (or similar) query string element, like we do with `?wipe=true`). This forces considering all stations fixed in `query_summary` even if they have an `ident` set, to cope with a reported misuse of DB-All.e

**Comment by edigiacomo** [comment]
I'm wondering how and if this could affect the `query_stations` for mobile data.

**Comment by edigiacomo** [comment]
> I'm wondering how and if this could affect the `query_stations` for mobile data.

I try to elaborate: suppose we have a dbadb with 5 BUFR messages from a single aeroplane with an instantaneous temperature at a fixed level (for the sake of simplicity). The proposed `query_summary` would return a single result, e.g. `mobile=1, ident=IDENT, latmin=LATMIN, latmax=LATMAX, lonmin=LONMIN, lonmax=LONMAX, datemin=DATEMIN, datemax=DATEMAX, var=B12101, level=103,2000,1000000, trange=254,0,0`.

On the other hand, `query_stations` return 5 results and `query_station_data` return 5 times the constant data (e.g. the name of the aeroplane).

Maybe I'm missing something, but it seems that these implementations wouldn't be consistent.

Moreover: I can't understand now how many stations are in the dbadb of the example above (one or five).

**Comment by spanezz** [comment]
The idea is that for that mobile station, `query_stations` returns 1 result, and `query_station_data` returns only one time the constant data.

I don't know if there would be trouble about the station data. Things like the name of the aeroplane would probably be the same, but other things, like the type of aircraft, could change over time if they use different planes for the same route. We would need to discuss with a field expert how to handle that kind of not-measured, not-changing-often-but-not-immutable data.

**Comment by edigiacomo** [comment]
We'll handle this issue in #150.
