### ISSUE TITLE
ident sometimes seem case sensitive and other insensitive

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#153]
http://rmapv.rmap.cc/borinud/api/v1/dbajson/Pat1/1136998,4448905/fixed/254,0,0/103,2000,-,-/B15195/timeseries/2019/01/25?dsn=sample_fixed

when in one DB with data as show in the link above other data are loaded with ident lowercase are imported as ident is case insensitive, when you query the DB the query seem case sensitive.

I annotate here the problem to do not lost in memory

**Comment by spanezz** [comment]
dballe treats everything case sensitively.

MySQL, however, contrarily to what SQLite and PosgreSQL are doing, seems to match case insensitively by default:

```
MariaDB [test]> create table foo (name varchar(255) not null);
Query OK, 0 rows affected (0.031 sec)

MariaDB [test]> insert into foo values ("FoO");
Query OK, 1 row affected (0.008 sec)

MariaDB [test]> select * from foo where name="foo";
+------+
| name |
+------+
| FoO  |
+------+
1 row in set (0.001 sec)
```

Whereas, trying that in PostgreSQL or SQLite, I get no matches as I would expect.

This is because the default charset and collation order in MySQL is historically [case insensitive Swedish](https://stackoverflow.com/questions/5629111/how-can-i-make-sql-case-sensitive-string-comparison-on-mysql) (!!).

I would be very happy to change this is DB-All.e, to make it uniform across databases.

Would it be ok if DB-All.e at some point started to be case sensitive on reports and idents even on MySQL?

**Comment by dcesari** [comment]
I agree on the default being case-sensitive, it is more intuitive, following the de facto standard in UNIX world.
At the moment Libsim forces the network (report) to lowercase, while nothing special is done on ident, it is trivial to remove this lowercasing, this may trigger some unexpected behavior in badly coded scripts/procedures, but i think this should not prevent us to do the change.
