### ISSUE TITLE
Python API: bindings for core::Data

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/dballe#158]
```python
import dballe
from datetime import datetime

db1 = dballe.DB.connect("sqlite://:memory:")
db1.reset()

with db1.transaction() as tr1:
    tr1.insert_data({
        "lon": 1212345,
        "lat": 4312345,
        "rep_memo": "test1",
        "datetime": datetime.now(),
        "level": (103, 2000),
        "trange": (254, 0, 0),
        "B12101": 0
    }, can_add_stations=True)

# rep_memo
db2 = dballe.DB.connect("sqlite://:memory:")
db2.reset()
with db1.transaction() as tr1, db2.transaction() as tr2:
    for row in tr1.query_data():
        data = row.data
        data["rep_memo"] = "test2"
        tr2.insert_data(data, can_add_stations=True)

with db2.transaction() as tr2:
    for row in tr2.query_data():
        print("rep_memo: {}==test2? {}".format(
            row["rep_memo"],
            row["rep_memo"] == "test2"
        ))

# report
db2 = dballe.DB.connect("sqlite://:memory:")
db2.reset()
with db1.transaction() as tr1, db2.transaction() as tr2:
    for row in tr1.query_data():
        data = row.data
        data["report"] = "test2"
        tr2.insert_data(data, can_add_stations=True)

with db2.transaction() as tr2:
    for row in tr2.query_data():
        print("report:   {}==test2? {}".format(
            row["report"],
            row["report"] == "test2"
        ))
```

The script has a non-deterministic behaviour on Fedora 24 (dballe-8.0-2):

```
[edigiacomo@ventiquattro ~]$ python3 test.py 
rep_memo: test1==test2? False
report:   test2==test2? True
[edigiacomo@ventiquattro ~]$ python3 test.py 
rep_memo: test2==test2? True
report:   test2==test2? True
```

With Fedora 28 (dballe-8.0-2) I can't reproduce the issue (the tests are always `True`), but maybe I'm unlucky - or lucky :grimacing:

**Comment by spanezz** [comment]
One possible reason could be because from python 3.6 (and [officially](https://mail.python.org/pipermail/python-dev/2017-December/151283.html) from python 3.7) python dicts preserve insertion order instead of having a nondeterministic ordering.

I still need to study the example and the code and the example a bit more to do a proper diagnosis, though.

**Comment by spanezz** [comment]
I found the issue: when doing `row.data`, both `rep_memo` and `report` get set in the dict, so that one can query them either way. However, when you set `rep_memo` and then insert, insert gets a dict with both `rep_memo` and `report` set. It iterates its contents to fill the data record to insert, and the last value overrides the first one, so what is set in the data record depends on the order in which the dict iterates.
Dicts iterate in an unpredictable order in pyhon < 3.6, and predictable from 3.6 onwards, which explains the results you are getting.

This bug shows however how it is problematic to work with dicts where the same value can be found in two places, and I'm now considering implementing some other way to carry data from cursor to insert that is not a real dict, and which can take aliases into account.

**Comment by spanezz** [comment]
Such a way to carry data looks like it could be a binding of core::Data in python, instead of exporting/exporting them to dicts. Of course, the possibility of using also dicts as inputs should be preserved.

**Comment by spanezz** [comment]
Question: whether the result of `cur.data` will be a `dict` or a `dballe.Data`, it may carry database IDs inside, like `ana_id`. When using it for insert into another database, that ID can cause unexpected behaviour, like inserting using a different station, or using a station ID that does not exist.

Potential solutions:

* always ignore IDs on insert; however, sometimes one wants to set `ana_id` instead of all the station information, and this would be broken if `ana_id` is ignored.
* implement something like `data.clear_ids()` (which already exists in C++) that would need to be called when taking data from one database and inserting it into another one.
* alternatively, implement a different version of `cursor.data` (like `cursor.export_data`) that gives a `dballe.Data` without database IDs, useful for export.
* on insert, check if the coordinates have been set in the record, and if so ignore ana_id.

Preferences?

**Comment by spanezz** [comment]
Ok, now `cursor.data` returns a `dballe.Data` object that behaves like a `dict` but handles aliased values correctly (`rep_memo`/`report`, `datetime`/`year`,`month`,…, `level`/`ltype1`,`l1`,…, and so on).

I added `cursor.data_dict` to get a dict instead.

The only missing thing is to decide what to do about the IDs, as detailed above. Let's talk about it on monday.

**Comment by spanezz** [comment]
After a phone call we decided for "on insert, check if the coordinates have been set in the record, and if so ignore ana_id"

**Comment by spanezz** [comment]
While working on this, I also discovered that, when inserting with only `ana_id` and no other station data set, and inserting multiple variables with different `ana_id`, only the first `ana_id` succeeds, and the others would raise the error `batch station has different id than the station we are using to look it up`.

I have fixed that, too.
