### ISSUE TITLE
python3-dballe package does not install egg-info

### ISSUE THREAD

**Issue by lidiabressan** [ARPA-SIMC/dballe#192]
ciao,
python3-dballe package does not install egg-info, so using pip the package doesn't see dballe installed.

in my setup.py:
```
    install_requires= [ 'dballe>=8.0', 'numpy'],
```

```
python3 setup.py installProcessing dependencies for udballe==1.0
.....
Searching for dballe
Reading https://pypi.org/simple/dballe/
Couldn't find index page for 'dballe' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for dballe
error: Could not find suitable distribution for Requirement.parse('dballe')
```
how can I do to check dependencies from dballe in my package?

Paolo e Lidia

**Comment by edigiacomo** [comment]
As you can read in the log you pasted, pip fails to retrieve dballe from pypi - because [dballe is not published in pypi][1].

I think that you are trying to install dballe inside a virtualenv and I think that it's not possible. In this case, you can try installing dballe with dnf, then creating the virtualenv with  `python3 -mvenv --system-site-packages' (see `python3 -mvenv --help` for an explanation of the option) and finally running your `python3 setup.py install`.


[1]: https://pypi.org/search/?q=dballe

**Comment by lidiabressan** [comment]
That's the case. dballe is already installed and i use a virtualenv with system-site-packages, but my python3 setup.py install fails because it misses the dballe dependency.

**Comment by edigiacomo** [comment]
Thank you for the additional info.

I think that listing dballe in the `install_requires` is quite useless: dballe is not published on pypi, so you still have to manually install the package using `dnf`.

The `install_requires` packages should be published in a pip repository (e.g. pypi.org): `pip install --system-site-packages` checks for that packages in the system dirs _and then_ in pypi (where it should be found).

Then, the solution to your problem is:

1. Write in the README of your project that the user has to manually install dballe.
2. Remove dballe from `install_requires`.
3. If you're writing a spec file, add `python3-dballe >= 8.0` to your `Requires` and `BuildRequires` (you also forgot to mention that you are writing a spec file, isn't it? :smile: )

If the problem is "how can I distribute dballe on pypi?", then the problem is broader, very difficult and I don't see the point in our use cases.

**Comment by lidiabressan** [comment]
ah ok, thanks! 
For point 3, I'm not writing a spec file (I don't think that I need it, right?).
If I understood it right, so dballe is an hidden installation in my python-system, which uses it but it doesn't know that it is there? Therefore I can use it but I cannot check for its dependency with python?

**Comment by edigiacomo** [comment]
> For point 3, I'm not writing a spec file (I don't think that I need it, right?).

It seems that my whistleblower in Bologna was wrong! In order to know if you don't need a spec file, I'd need to know what you're trying to do :) Write me an email, if you want/need.

> If I understood it right, so dballe is an hidden installation in my python-system, which uses it but it doesn't know that it is there? Therefore I can use it but I cannot check for its dependency with python?

Exactly! A virtualenv with the `--system-site-packages` can see the system packages.

```
$ python3 -mvenv env
$ env/bin/python -c "import dballe"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'dballe'
```

```
$ python3 -mvenv --system-site-packages env
$ env/bin/python -c "import dballe"
```

**Comment by pat1** [comment]
il problema non è avere dballe in pypi ma avere le dipendenze rislte correttamente in setuptools.
Il problema si genera impostando la dipendenza in setup.py e volendo eseguire setup.py install.
Si può rimuovere la dipendenza ma poi volendo fare un rpm le macro fedora sono in grado di utilizzare le dipendenze di setup.py in modo automatico e bisognerebbe reinserire le dipendenze manualmente. Quindi le dipendenze dovrebbero essere specificate in due punti: in setup.py (tutte meno dballe) e poi in pacchetto.spec (riscrivendole tutte traducendole col nome del pacchetto e inserendo dballe).
Avendo da costruire molti pacchetti mi parrebbe più corretto e pulito aggiungere un egg-info con i metadati al pacchetto python3-dballe e proseguire in modo più lineare anche se non risulta obbligatorio:
https://fedoraproject.org/wiki/Packaging:Python_Eggs

**Comment by edigiacomo** [comment]
Quindi il problema è "come faccio a fare un pacchetto python senza scrivere lo spec?" - a cui aggiungo, per intuizione, un "per poterlo distribuire su copr?".

A questo punto, ti chiedo: ha senso mettere su copr molti pacchetti e poi mantenerli, dovendo ad ogni aggiornamento di un pacchetto upstream o sua dipendenza (quindi siamo nell'ordine del molti * molti) rifare il pacchetto?

Secondo me ti converrebbe fare un virtualenv in cui installi le tue dipendenze con pip e usi i pacchetti di sistema laddove serve. Puoi anche fare il "pinning" delle tue dipendenze, se vuoi essere certo di avere una certa versione di un certo pacchetto (e.g. `django==1.11`, che può essere sia quella di sistema che da pypi).

In questo modo, non devi (1) fare nessun pacchetto e (2) puoi usare i pacchetti di sistema laddove non vuoi scaricarli da pip. Così è ancora più leggero da mantenere.

Se hai poche applicazioni e i molti pacchetti Python che devi fare sono le dipendenze alle applicazioni (rmap?), potresti fare uno spec solo per l'applicazione portandoti dietro un virtualenv generato a tempo di pacchettizzazione. In quel modo, avresti un solo pacchetto da gestire.

Chiudo la issue e ti propongo di parlarne via mail in modo più dettagliato, per capire di quali/quanti pacchetti parliamo. Se poi vediamo che la soluzione è aggiungere gli egg metadata a dballe e wreport apriamo issue appropriata e risolviamo.

**Comment by pat1** [comment]
https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#_files_to_include
però da creare senza setuptools non è proprio semplice semplice...
