### ISSUE TITLE
json input format not listed in dbamsg help

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/dballe#202]
```
dbamsg help convert
Usage: dbamsg convert [options] [filter] filename [filename [...]]
...
  -t, --type=type                  format of the input data ('bufr', 'crex',
                                   'csv')
```
But `dbamsg -t json -d bufr` works. Are there any other valid input formats not listed in the doc? Of course the same holds for other dbamsg subcommands.

**Comment by spanezz** [comment]
I checked in the code, and it's `csv`, `json`, `bufr`, `crex`, and `auto`. `auto` looks inside the input file to determine if it's BUFR or CREX, but can't autodetect CSV or JSON, and I'm king of tempted of not documenting it, and say that if one specifies `--type`, one has a type to specify.

I've fixed the documentation about input types. Output types like `--dest` are still mostly only `bufr` and `crex`, although looking at the code it's high time it's refactored to promote at least JSON to a first-class citizen.

**Comment by spanezz** [comment]
JSON is now available like BUFR and CREX everywhere an encoding may be specified, be it in command line tools and in the APIs.

I have not done the same for CSV, because we currently have 2 or 3 different CSV layouts. If we want to standardize on one (like the output of `dbamsg dump --csv --interpreted`), I can do the same with CSV
