### ISSUE TITLE
import from json data do not work for integer data type

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#212]
with data as
```
{"ident":null,"network":"fixed","lon":1271900,"date":"2020-03-20T00:00:00Z","lat":4617400,"data":[{"vars":{"B01019":{"v":"2_42400"},"B07030":{"v":261},"B07031":{"v":261}}},{"timerange":[254,21600,0],"vars":{"B12001":{"a":{"B08197":1,"B33196":1},"v":null},"B12101":{"v":27545},"B13003":{"v":42}},"level":[103,2000,null,null]},{"timerange":[254,32400,0],"vars":{"B12001":{"a":{"B33196":1},"v":null},"B12101":{"a":{"B33196":1},"v":null},"B13003":{"a":{"B33196":1},"v":null}},"level":[103,2000,null,null]},{"timerange":[254,43200,0],"vars":{"B12001":{"a":{"B33196":1},"v":null},"B12101":{"a":{"B33196":1},"v":null},"B13003":{"a":{"B33196":1},"v":null}},"level":[103,2000,null,null]}]}
```
we get errors:
```
dbadb import --wipe-first -t json --dsn=sqlite:line.sqlite line.json
Cannot parse JSON message #0: Value 27545 is outside the range [0,655.34] for B12101 (TEMPERATURE/DRY-BULB TEMPERATURE) at offset 0.
Message #0 cannot be parsed: ignored
```
```
 dbamsg convert -t json -d bufr line.json > oi.bufr
Cannot parse JSON message #0: Value 27545 is outside the range [0,655.34] for B12101 (TEMPERATURE/DRY-BULB TEMPERATURE) at offset 0.
No interpreted information available: is a recoding enough?
No BUFREX raw data to attempt low-level bufrex recoding
```
integer values should be managed as in fortran API and described  at http://www.raspibo.org/wiki/index.php?title=Gruppo_Meteo/RFC-rmap#Variabile

Is it possible to discriminate by point presence in the field ?

**Comment by edigiacomo** [comment]
We introduced the behaviour some time ago to fix #76. Above, a more verbose explanation of the problem.

The fix that you propose is possibile and easy to implement but, as I already pointed out, this can lead to some problems: in JavaScript there's no difference between integer and float ([everything is a "number"](https://developer.mozilla.org/en-US/docs/Glossary/Number)), then a producer could create a float value with a generic library without guarantees that the output value will have the point. 

For example, in Javascript (press F12 to try in the console of your browser):

```
> value = {"v": 12.0}
Object { v: 12 }
```

In Python you don't have this problem, because `json.dumps({"v":12.0})` will return `{"v":12.0}`, but from the next version it could return `{"v":12}`.

This means that every float value in JSON can be potentially misunderstood by the dballe importer. Then, you are implicitly forcing to use the string or the integer value, because it's the only format that will produce an unambiguous value.

A solution is to deprecate the integer representation and use only the float representation for scaled values and the string representation for unscaled values.

**Comment by pat1** [comment]
the javascript problem is really a problem ?
we are going to use javascript with jsonline ?
we are going to use javascript with jsonline with integer ?
I think we can use integer for now and deprecate its use adopting the float representation for scaled values and the string representation for unscaled values in next RMAP specification and dballe release; I need some time to advise some data providers and change  all firmware station installed around the world ; integer representation is the default over MQTT

**Comment by edigiacomo** [comment]
> the javascript problem is really a problem ?
> we are going to use javascript with jsonline ?
> we are going to use javascript with jsonline with integer ?

The point wasn't JavaScript, but that you can have that problem with any language unless you don't have full control over the implementation of the JSON encoder. 

> I think we can use integer for now and deprecate its use adopting the float representation for scaled values and the string representation for unscaled values in next RMAP specification and dballe release; I need some time to advise some data providers and change all firmware station installed around the world ; integer representation is the default over MQTT

It's seems to me that the MQTT JSON has nothing to do with this problem, because that JSON is different from the dballe JSON and it has its own parser that converts MQTT topic + payload in BUFR https://github.com/r-map/rmap/blob/master/mqtt2bufr/mqtt2bufr.py.

I recall you that the problem of this issue was reported because an external provider was trying to write a JSON without using dballe, you suggested to use the integer or float representation and Davide pointed out that the integer representation had some problems.

**Comment by pat1** [comment]
Ho verificato e attualmente su rmap.cc la conversione viene effettuata sempre tramite dballe quindi evidentemente fino a ora non ho avuto forniture con interi.
Ho tre forniture che si stanno attivando ora : CAE, Netsens e ARPA Piemeonte per Mistral
a tutte 3 sono state date indicazioni per usare gli interi, bisogna indirizzarle immediatamente alle stringhe facendo uscire una nuova versione di specifica.
Per quanto riguarda MQTT le specifiche erano esattamente le stesse del json; dobbiamo decidere se migrare anche in questo caso a stringhe o lasciare specifiche differenti ...

**Comment by edigiacomo** [comment]
Ok, I close this issue and we can talk about this problem via email or you can open an issue in the rmap repo.
