### ISSUE TITLE
Please improve the documentation!

### ISSUE THREAD

**Issue by lidiabressan** [ARPA-SIMC/dballe#225]
The documentation should be improved. 

Let me make an example: to understand how to read a simple data query, one should look into all the documentation and try to understand how the following work:
- cursorData and cursorDataDB (item that you cycle on a query, doc cursor page)
- from these you get a dballe.Data object, explained very little somewhere else (doc dballe types page), and apparently used only to insert data in db (so why to get it out of a query?)
- you can also do queries on the cursor by keys, but which keys? Without inside tips, it is impossible to understand that the keys are query parameters and that you need to look at the doc query parameters page.
- query parameters are different if you do a query or if you read one
 
It is confusing and it takes time and patience to look on several pages at once trying to put together and cross-reference the various small pieces. Without inside tips, who will ever take so much effort just to do and read a simple data query?

I haven't figured it out yet how to get attributes from a variable. I go with trials but these don't work:
- row['variable'].get_attrs()
- row['B33196']

Please help and improve the documentation!

Thanks 

Lidia

**Comment by spanezz** [comment]
I'm sorry you are finding understanding how dballe works a frustrating experience. We have a specialization problem where I, as the person writing dballe, I'm not really using it for my work besides development, and because of the cognitive dissonance of that, it's hard for me to write relevant documentation.

Your feedback and requests are precious for me to understand where documentation is needed and in what form, and I can try to improve it as a consequence. It's a bit of a chicken and egg problem, though, where you need to first become frustrated by the lack of documentation in order to trigger documentation to be written.

I would encourage all the people who use dballe to also participate in the documentation process, contributing examples and recipes from their work. So far I think this has happened through sharing of insider tips, and I think it has rarely made it from there to proper documentation contributions.

This said, I'll now try to add an HOWTO with some recipes for working with attributes

**Comment by spanezz** [comment]
I added these example recipes to the documentation:
https://github.com/ARPA-SIMC/dballe/blob/master/doc/python_how/attributes.rst

Let me know if they can be enough of a starting point for working with attributes.

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
