### ISSUE TITLE
API to get all B, level, trange

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#234]
How we can get all available B, level, trange to write cached tables (with descriptions) for example for other languages (javascript) from python ?

**Comment by spanezz** [comment]
Sorry, I did not understand the question. Can you give me an example of what you would like to get?

**Comment by pat1** [comment]
sorry, I come from this problem:
https://github.com/ARPA-SIMC/cosudo/issues/1
for example we need to have the list of all available Bcodes from file /usr/share/wreport/dballe.txt that we can query to get description and build a table available for example in js web app to build user interface menu on summaries information without build those information every time run time.

**Comment by pat1** [comment]
we need to build something like this:
* https://github.com/r-map/rmap/blob/master/python/showdata/static/showdata/borinud.B.js
* https://github.com/r-map/rmap/blob/master/python/showdata/static/showdata/borinud.level.js
* https://github.com/r-map/rmap/blob/master/python/showdata/static/showdata/borinud.trange.js

**Comment by spanezz** [comment]
Currently, documentation and similar that are derived from Bcodes, levels, timeranges, are generated by the `doc/mksnippet` script, which could be expanded to generate other outputs, like JSON.

I would be happy to implement iteration for B tables in wreport's python APIs (if that's a thing you'd like, please open an issue for it). I would not add an API to enumerate level or timerange metadata just for creating those tables.

Possibly a simple way can be to also generate json versions of dballe.txt, level information, and timerange information, and package them in something like /usr/share/dballe.

Note that this would not be the equivalent of using `describe_level`, `describe_timerange`, and `describe_var`, because those algoritmically build a description based on the actual current values, not just B code and level type/timerange indicators.

Would the JSON option work for you?

**Comment by pat1** [comment]
waiting here:
ARPA-SIMC/cosudo#1

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
