### ISSUE TITLE
Method to delete duplicates station from dballe

### ISSUE THREAD

**Issue by bchiavarini** [ARPA-SIMC/dballe#265]
Hi, we are having a problem with our local DBalle because we have some stations that have been duplicated by mistake and that are now rising `selection station ID query returned 2 results` error when data are imported using Python API 
``` python
with db.transaction() as tr:
    tr.import_messages(msg, overwrite=True, update_station=True, import_attributes=True)
```
Is there a command to easily purge the database from these duplicated stations?

Thanks for your help

**Comment by spanezz** [comment]
There is no such a method in dballe at the moment, mainly because there's never been a need for it. dballe should never duplicate stations, and to the best of my knowledge we haven't seen it happen in our production databases.

If it happens, I think the best thing would be to figure out how it happens, and for that I'd need access to a database where it happens, and information about what operations led it to be that way.

Rather than put effort in coding for a "feature" needed to recover after a recurring issue, I would put effort in understanding how the issue happens and on making it not happen
