### ISSUE TITLE
Is CNF still needed?

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/dballe#61]
The old Debian packages of CNF I made years ago are in need of cleaning up, as they cannot be in Debian anymore as they are.

Rather than cleaning up those packages, I would prefer to remove dependency of CNF. I recall there has been a mention of it not being really needed anymore in the days of modern Fortran, is that correct, and can I just get rid of it? Does anyone have a link for how to interface C and Fortran without the extra dependency?

**Comment by dcesari** [comment]
Pat1 and I warmly suggest the use of F2003 iso_c_binding module which is the standard, available on modern compilers without any extra dependency; a partial but good explanation is found on page 30 of ftp://ftp.nag.co.uk/sc22wg5/n1551-n1600/n1579.pdf, see also the exciting project [fortrangis](https://github.com/dcesari/fortrangis) :-).

My suggestion is to cleanup fortran/binding.cc of all the CNF stuff and expose just a plain C interface (pointers, args by value, char* are acceptable) then I can take the commitment to rewrite dballef.h in the form of a fortran module using the iso_c_binding (and possibly some fortran layer to terminate strings and smooth the interface) to expose the C functions in binding.cc to Fortran.

A critical point is the dbahandle which is a pointer, kindly converted to an integer by CNF, it would be a hard and pointless work to keep it as an integer with iso_c_binding. My proposal is to convert it to a Fortran opaque derived type as done in fortrangis for gdal
```
TYPE,BIND(C) :: GDALDatasetH
  PRIVATE
  TYPE(c_ptr) :: ptr = C_NULL_PTR
END TYPE GDALDatasetH
```
rather than leave it in fortran as an explicit C pointer (still possible), this enforces a clean fortran programming style. Both approaches (pointer or derived type) require however change of legacy fortran programs, @pat1 is this acceptable?

**Comment by spanezz** [comment]
The handle is not a problem, I already manage it as an integer, CNF is not doing any conversion there.
I'll create a new branch, clean up binding.cc and ask for your input.

**Comment by spanezz** [comment]
I had a look at the PDF and in branch `issue61` I have unwrapped presentati, arrivederci and preparati from CNF. Is it good enough like that? Tomorrow I'm available online to work on this if you are.

**Comment by dcesari** [comment]
Added a corresponding dballef.f90 to the branch, it builds, untested, i'll be online friday afternoon

**Comment by spanezz** [comment]
After a tandem work with Davide, the branch issue61 now builds without CNF.

Now that branch needs a bit of road testing, and then a merge into master.

**Comment by pat1** [comment]
in altre implementazioni ho dovuto gestire la dimensione di size_t e utilizzare il preprocessore per gestire le piattaforme a 32 o 64 bit:
interface vdf4f_write
#if SIZEOF_SIZE_T == 8
  module procedure vdf4f_write_amd64
#endif
  module procedure vdf4f_write_i386
end interface

e in ogni procedura il size_t doveva essere gestito opportunamente.
Se nelle api non ci sono size_t il problema non si pone.

Poi sulle stringhe segnalo http://fortranwiki.org/fortran/show/Generating+C+Interfaces#strings
ma su alcune versioni di gfortran non avevo ancora a disposizione C_NULL_CHAR

**Comment by dcesari** [comment]
Rpm package builds and libsim works with only the expected modifications, from my point of view we can close the issue.
