### ISSUE TITLE
adding to query "best" a new option query "last"

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#80]
Evaluate the possibility to add a new option to "query".

The option "last" will be very useful to show the last data for each station in the period.
For example to show the last "snow depth" observed in a day on a map.

**Comment by spanezz** [comment]
It sounds doable, with some work.

When using `query=last`, should the results contain no datetime information, or do you want to know the date and time relative to the value that was last seen for a variable?

**Comment by pat1** [comment]
I want to know the date and time relative to the value that was last seen for a variable
We need to extimate the work for this

**Comment by spanezz** [comment]
If the data exists for the given station at the same time but at different levels or timeranges, what should I do?

I would say `DB-All.e` should return one result for each level/timerange, unless one explicitly filters by level/timerange.

I'd like to double check with you, though, because I don't have the full details of the user story here.

**Comment by pat1** [comment]
I think at the same standard behaviour  but for any unique keys (lat,lon,network,ident,level,timerange,var) I get only one (last) value.
What is best for network, last is for datetime.
