### ISSUE TITLE
error with dbadb delete

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/dballe#90]
dbadb delete --dsn="mysql:///rmap" yearmax=2017 monthmax=04 daymax=10 
cannot execute 'ROLLBACK': MySQL server has gone awaycannot execute 'DELETE FROM data WHERE id IN (631846,631848,631850,631849,631851,631852,631856,631855,631859,631860,631862,631861,631877,631878,631880,631879,631881,631882,631884,631883,631899,631900,631902,631901,631903,631904,631906,631905,631921,631922,631924,631923,1760857,1760855,1760860,1760858,1760864,1760862,1760866,1760865,1760876,1760874,1760886,1760884,1760895,1760894,1760909,1760908,1760931,1760929,1760942,1760941,1760955,1760952,1761224,1761236,1761245,1761257,1761266,1761281,1761290,1761302,1:MySQL server has gone away

**Comment by pat1** [comment]
if I reduce the period the delete works

**Comment by spanezz** [comment]
I have no way to reproduce this, so I'm leaving it up to you to find out why this happens.

Please see https://dev.mysql.com/doc/refman/5.7/en/gone-away.html for an overview of what may be going bad.

Note that reconnection in the client is disabled in DB-All.e, because when enabled the MySQL state in the client can silently become inconsistent at any time. For example, DB-All.e might think it is still in the middle of a transaction, but that transaction has silently disappeared. Or the information about the database ID of a value that has just been inserted might silently become wrong.

https://dev.mysql.com/doc/refman/5.7/en/auto-reconnect.html has a list of all the things that might go wrong. Whoever wrote "you just have to issue the query again for the client to do an automatic reconnection. This assumes that you have automatic reconnection in the client enabled" has no clue about nontrivial database interaction, which seems to be the common case in the MySQL ecosystem.

Possible mitigations can be to increase `wait_timeout` in the server. How long did that query take to run?

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
