### ISSUE TITLE
dbadb export doesn't print explain statement

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/dballe#98]
`dbadb export` doesn't print `EXPLAIN` statements ([test.sqlite3.zip](https://github.com/ARPA-SIMC/dballe/files/1182804/test.sqlite3.zip) contains the test db).

```
$ DBA_EXPLAIN=yes dbadb stations --dsn=sqlite:test.sqlite3  test.bufr 2>&1 > /dev/null | head -n1
EXPLAIN
$ DBA_EXPLAIN=yes dbadb dump --dsn=sqlite:test.sqlite3  test.bufr 2>&1 >/dev/null | head -n1 
EXPLAIN 
$ DBA_EXPLAIN=yes dbadb export --dsn=sqlite:test.sqlite3  test.bufr 2>&1 > /dev/null | wc -c
0
```

I think the problem is that [`DB::export_msgs` use Driver::run_query_data()](https://github.com/ARPA-SIMC/dballe/blob/v7.23-1/dballe/db/v7/export.cc#L132) instead of [`cursors::run_data_query`](https://github.com/ARPA-SIMC/dballe/blob/v7.23-1/dballe/db/v7/cursor.cc#L544).

I tag the issue as enhancement because `dbadb dump` should use the same query of `dbadb export`.

**Comment by spanezz** [comment]
cursor::run_data_query loads the result into a Cursor, which isn't what's needed on export. However, indeed export needs an explain call. I'll implement it

**Comment by spanezz** [comment]
The difference between `dump` and `export` is that `dump` queries data (like in Fortran `voglioquesto`/`dammelo`), while `export` queries messages. The queries use different code paths because the sorting order needs to change in `V6` databases. The queries should be the same in `V7` databases, and only change in `ORDER BY` in V6 databases.

Now explain should also get called on export. I'm reassigning to you for review: is this sufficient for what you needed?

**Comment by edigiacomo** [comment]
Thanks!
